<a href="https://colab.research.google.com/github/quanvo06/remove-pdf-highlight/blob/main/Project_1_(Mini)_EDA_ChEMBL_Data_Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TẢI THƯ VIỆN CHEMBL

In [ ]:
! pip install chembl_webresource_client

Requirement already satisfied: chembl_webresource_client in /usr/local/lib/python3.12/dist-packages (0.10.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Requirement already satisfied: requests-cache~=1.2 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.3.2)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: cattrs>=22.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.6)
Requirement already satisfied: url-normalize>=2.0 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (3.0.0)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)

GỌI LỆNH NEW_CLIENT

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client as nc

SEARCH TỪ KHOÁ

In [ ]:
target = nc.target
target_query = target.search('Acetylcholinesterase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Drosophila melanogaster,Acetylcholinesterase,18.0,False,CHEMBL2242744,"[{'accession': 'P07140', 'component_descriptio...",SINGLE PROTEIN,7227
1,[],Homo sapiens,Acetylcholinesterase,16.0,False,CHEMBL220,"[{'accession': 'P22303', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Torpedo californica,Acetylcholinesterase,16.0,False,CHEMBL4780,"[{'accession': 'P04058', 'component_descriptio...",SINGLE PROTEIN,7787
3,[],Mus musculus,Acetylcholinesterase,16.0,False,CHEMBL3198,"[{'accession': 'P21836', 'component_descriptio...",SINGLE PROTEIN,10090
4,[],Rattus norvegicus,Acetylcholinesterase,16.0,False,CHEMBL3199,"[{'accession': 'P37136', 'component_descriptio...",SINGLE PROTEIN,10116
5,[],Electrophorus electricus,Acetylcholinesterase,16.0,False,CHEMBL4078,"[{'accession': 'O42275', 'component_descriptio...",SINGLE PROTEIN,8005
6,[],Bos taurus,Acetylcholinesterase,16.0,False,CHEMBL4768,"[{'accession': 'P23795', 'component_descriptio...",SINGLE PROTEIN,9913
7,[],Anopheles gambiae,Acetylcholinesterase,16.0,False,CHEMBL2046266,"[{'accession': 'Q869C3', 'component_descriptio...",SINGLE PROTEIN,7165
8,[],Bemisia tabaci,AChE2,16.0,False,CHEMBL2366409,"[{'accession': 'B3SST5', 'component_descriptio...",SINGLE PROTEIN,7038
9,[],Leptinotarsa decemlineata,Acetylcholinesterase,16.0,False,CHEMBL2366490,"[{'accession': 'Q27677', 'component_descriptio...",SINGLE PROTEIN,7539
10,[],Nephotettix cincticeps,Ace-orthologous acetylcholinesterase,16.0,False,CHEMBL2366514,"[{'accession': 'Q9NJH6', 'component_descriptio...",SINGLE PROTEIN,94400
11,[],Gallus gallus,Acetylcholinesterase,16.0,False,CHEMBL3227914,"[{'accession': 'P36196', 'component_descriptio...",SINGLE PROTEIN,9031
12,[],Danio rerio,Acetylcholinesterase,16.0,False,CHEMBL3308995,"[{'accession': 'Q9DDE3', 'component_descriptio...",SINGLE PROTEIN,7955
13,[],Aedes aegypti,Acetylcholinesterase,16.0,False,CHEMBL4295607,"[{'accession': 'Q6A2E2', 'component_descriptio...",SINGLE PROTEIN,7159
14,[],Homo sapiens,Protein CutA,16.0,False,CHEMBL6067022,"[{'accession': 'O60888', 'component_descriptio...",SINGLE PROTEIN,9606
15,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL5752,"[{'accession': 'Q95P20', 'component_descriptio...",SINGLE PROTEIN,7370
16,[],Plutella xylostella,Acetylcholinesterase,15.0,False,CHEMBL2242729,"[{'accession': 'Q8MZM0', 'component_descriptio...",SINGLE PROTEIN,51655
17,[],Musca domestica,Acetylcholinesterase,15.0,False,CHEMBL2242743,"[{'accession': 'Q7YWJ9', 'component_descriptio...",SINGLE PROTEIN,7370
18,[],Pediculus humanus capitis,Acetylcholinesterase,15.0,False,CHEMBL2362988,"[{'accession': 'A2PZ98', 'component_descriptio...",SINGLE PROTEIN,121226
19,[],Spodoptera litura,Acetylcholinesterase,15.0,False,CHEMBL2366422,"[{'accession': 'C5IU80', 'component_descriptio...",SINGLE PROTEIN,69820
20,[],Laodelphax striatella,Acetylcholinesterase,15.0,False,CHEMBL2366446,"[{'accession': 'K4JQ36', 'component_descriptio...",SINGLE PROTEIN,195883
21,[],Schizaphis graminum,Acetylcholinesterase,15.0,False,CHEMBL2366511,"[{'accession': 'Q9BMJ1', 'component_descriptio...",SINGLE PROTEIN,13262
22,[],Homo sapiens,Cholinesterases; ACHE & BCHE,14.0,False,CHEMBL2095233,"[{'accession': 'P06276', 'component_descriptio...",SELECTIVITY GROUP,9606
23,[],Rattus norvegicus,Acetylcholinesterase and butyrylcholinesterase...,14.0,False,CHEMBL2111475,"[{'accession': 'P37136', 'component_descriptio...",SELECTIVITY GROUP,10116
24,[],Caenorhabditis elegans,Acetylcholinesterase 1,14.0,False,CHEMBL3341583,"[{'accession': 'P38433', 'component_descriptio...",SINGLE PROTEIN,6239
25,[],Equus caballus,Butyrylcholinesterase,11.0,False,CHEMBL5077,"[{'accession': 'Q9N1N9', 'component_descriptio...",SINGLE PROTEIN,9796
26,[],Equus caballus,Cholinesterase,11.0,False,CHEMBL5763,"[{'accession': 'P81908', 'component_descriptio...",SINGLE PROTEIN,9796
27,[],Canis lupus familiaris,Cholinesterase,11.0,False,CHEMBL4630814,"[{'accession': 'P32750', 'component_descriptio...",SINGLE PROTEIN,9615
28,[],Mus musculus,Cholinesterase,10.0,False,CHEMBL2528,"[{'accession': 'Q03311', 'component_descriptio...",SINGLE PROTEIN,10090
29,[],Rattus norvegicus,Butyrylcholinesterase,10.0,False,CHEMBL3403,"[{'accession': 'Q9JKC1', 'component_descriptio...",SINGLE PROTEIN,10116
30,[],Homo sapiens,Cholinesterase,5.0,False,CHEMBL1914,"[{'accession': 'P06276', 'component_descriptio...",SINGLE PROTEIN,9606

CHỌN HOMOSAPIEN

In [ ]:
selected_target = targets.target_chembl_id[1]
selected_target

'CHEMBL220'

CÁC THỬ NGHIỆM TRÊN Dopamine D4

In [ ]:
activity = nc.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:
activity = nc.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [ ]:

df = pd.DataFrame.from_dict(res)
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32113,[],CHEMBL676182,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(4) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,20.0
1,None,None,33284,[],CHEMBL676182,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(4) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,57.0
2,None,None,38260,[],CHEMBL676182,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(4) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,3.0
3,None,None,38261,[],CHEMBL676182,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(4) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,7.0
4,None,None,39389,[],CHEMBL676182,Binding affinity to cloned human Dopamine rece...,B,None,None,BAO_0000190,...,Homo sapiens,D(4) dopamine receptor,9606,None,None,IC50,nM,UO_0000065,None,16.0

In [ ]:
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9726,None,643508,27216797,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,411.0
9727,None,643509,27216800,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,395.0
9728,None,643510,27216803,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,625.0
9729,None,643511,27216806,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,320.0
9730,None,643512,27216809,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,11.0

LƯU LẠI Ở CSV file hoatchat_data.csv

In [ ]:
df.to_csv('hoatchat_data.csv', index=False)

LOẠI BỎ CÁC DỮ LIỆU THIẾU THÔNG TIN

In [ ]:
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_7159/3852201246.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9726,None,643508,27216797,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,411.0
9727,None,643509,27216800,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,395.0
9728,None,643510,27216803,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,625.0
9729,None,643511,27216806,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,320.0
9730,None,643512,27216809,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,11.0

ĐẾM SỐ LƯỢNG THẬT SỰ

In [ ]:
len(df2.canonical_smiles.unique())

6898

BỎ LẶP LẠI

In [ ]:
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,33969,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.75
1,None,None,37563,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.1
2,None,None,37565,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,50.0
3,None,None,38902,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.3
4,None,None,41170,[],CHEMBL643384,Inhibitory concentration against acetylcholine...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,uM,UO_0000065,None,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9724,None,643506,27216791,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,5090.0
9726,None,643508,27216797,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,411.0
9727,None,643509,27216800,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,395.0
9728,None,643510,27216803,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,625.0
9729,None,643511,27216806,[],CHEMBL5732338,Inhibition Assay: Acetylcholinesterase extract...,B,None,None,BAO_0000190,...,Homo sapiens,Acetylcholinesterase,9606,None,None,IC50,nM,UO_0000065,None,320.0

CHỌN 3 CỘT CHÍNH

In [ ]:
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.0
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.0
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.0
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.0
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.0
...,...,...,...
9724,CHEMBL6054495,COc1cc(N)c(I)cc1C(=O)NCC1CCN(CC2CCCCC2)CC1,5090.0
9726,CHEMBL5755069,Nc1cc(O)c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc1Cl,411.0
9727,CHEMBL5791030,CCOc1cc(N)c(Cl)cc1C(=O)CCC1CCN(CC2CCCCC2)CC1,395.0
9728,CHEMBL5799857,Nc1cc(OCCF)c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc1Cl,625.0
9729,CHEMBL5833354,CON=C(CCC1CCN(CC2CCCCC2)CC1)c1cc(Cl)c(N)cc1OC,320.0

LƯU

In [ ]:
df3.to_csv('hoatchat_data_2_daxuly.csv', index=False)

ĐỌC FILE

In [ ]:
df4 = pd.read_csv('hoatchat_data_2_daxuly.csv')

PHÂN LOẠI HOẠT CHẤT

In [ ]:
bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")

THÊM VÀO DF

In [ ]:

bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL133897,CCOc1nn(-c2cccc(OCc3ccccc3)c2)c(=O)o1,750.0,active
1,CHEMBL336398,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC1CC1,100.0,active
2,CHEMBL131588,CN(C(=O)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F)c1ccccc1,50000.0,inactive
3,CHEMBL130628,O=C(N1CCCCC1)n1nc(-c2ccc(Cl)cc2)nc1SCC(F)(F)F,300.0,active
4,CHEMBL130478,CSc1nc(-c2ccc(OC(F)(F)F)cc2)nn1C(=O)N(C)C,800.0,active
...,...,...,...,...
6893,CHEMBL6054495,COc1cc(N)c(I)cc1C(=O)NCC1CCN(CC2CCCCC2)CC1,5090.0,intermediate
6894,CHEMBL5755069,Nc1cc(O)c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc1Cl,411.0,active
6895,CHEMBL5791030,CCOc1cc(N)c(Cl)cc1C(=O)CCC1CCN(CC2CCCCC2)CC1,395.0,active
6896,CHEMBL5799857,Nc1cc(OCCF)c(C(=O)CCC2CCN(CC3CCCCC3)CC2)cc1Cl,625.0,active
6897,CHEMBL5833354,CON=C(CCC1CCN(CC2CCCCC2)CC1)c1cc(Cl)c(N)cc1OC,320.0,active

LƯU DF5

In [ ]:
df5.to_csv('hoatchat_data_3_daxuly_dachuanhoa.csv', index=False)